### ISSUE TITLE
Errors are not shown in frontend

### ISSUE THREAD

**Issue by Nikos410** [interaapps/pastefy#12]
Hey there, 

if creating a paste fails, for example because it is too long (#11) the frontend keeps showing the loading spinner, so it is not visible that something went wrong:
![image](https://user-images.githubusercontent.com/20876882/142769155-2f94b116-c701-4a85-8619-0d6fa5d74d65.png)

I'm running pastefy using the docker image with the tag `latest`

**Comment by JulianFun123** [comment]
Hey, thanks for letting me know. I fixed the bug in the latest commit and released 6.3.3

**Comment by Nikos410** [comment]
Awesome, thanks for the quick fix :)
