### ISSUE TITLE
Still confused how to use it

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [interaapps/pastefy#19]
So in default pastes get deleted after what time? 

Also is there a way to set a default delete days or something and is there a way to enable encryption by default 

PS: i use docker-compose version

**Comment by JulianFun123** [comment]
Pastes do not get deleted after time and there is currently no option to do it. You can enable encryption for pastes by either checking the checkbox or entering a password. There is currently no way to set it by default. But thank you, I'll write that down and add it in the future.

**Comment by EsmailELBoBDev2** [comment]
Your welcome and thank you that you will implement them in the future

**Comment by EsmailELBoBDev2** [comment]
Well to wrap it up!
As self hosting, I want to host it but i'm afraid of the future where you know I will get so much of pastes and run out of space so as me, I want option to auto delete pastes after time as default. and set option to user to select that too (and make it like a max year for deletion) 

And maybe add option to force login to paste or make delete button work without need to login (as i noticed i can't delete pastes without account)
