### ISSUE TITLE
Authorization callback URL

### ISSUE THREAD

**Issue by NoverNobida** [interaapps/pastefy#21]
What is the `Authorization callback URL` of Github OAuth?

**Comment by JulianFun123** [comment]
The callback URL should be ...`/api/v2/auth/oauth2/github/callback`

**Comment by NoverNobida** [comment]
It works well!

**Comment by NoverNobida** [comment]
Would you consider adding an independent account system instead of relying on a third party?

**Comment by JulianFun123** [comment]
Using OAuth2 makes it much easier for the user by just clicking a button and being logged in. It's also easier for the self-hoster because they just add a clientid and a secret and not have to look at an own login-system which is also a source for security issues.
