### ISSUE TITLE
Feature Request - UAC/Admin

### ISSUE THREAD

**Issue by modem7** [interaapps/pastefy#24]
Would it be possible to have some form of user access control/user admin panel?

E.g. There is already oauth which is awesome, but there's no way to stop a bad actor from creating multiple accounts/unable to manage current user accounts. 

An admin panel w/ an "accept/deny new user account", manage users/delete users/pastes or invite link to the service would be awesome.

**Comment by JulianFun123** [comment]
This has been added under https://github.com/interaapps/pastefy/releases/tag/6.5.0
