### ISSUE TITLE
Feature Request - Logout button location

### ISSUE THREAD

**Issue by modem7** [interaapps/pastefy#25]
The logout button is currently quite far down in the settings. 

From a new user perspective, it may make sense to have the logout button in roughly the same position/text size/font as the login button.

**Comment by modem7** [comment]
Maybe around here?
![image](https://user-images.githubusercontent.com/4349962/156857549-a7e9e9f0-caa9-4083-be4a-d9ef12484cfd.png)

That way it's out of the way, but still available.

**Comment by JulianFun123** [comment]
I don't think that this looks good either
