### ISSUE TITLE
No Delete/Edit option on my container

### ISSUE THREAD

**Issue by tamimology** [interaapps/pastefy#28]
I do not have any delete/edit option on any of my pastes.

![image](https://user-images.githubusercontent.com/90429593/162645324-35c1903b-888a-4354-b2f5-40e2764d003b.png)

Below is my compose file:

  pastefy:
    container_name: pastefy
    restart: unless-stopped
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: pastefy
      DATABASE_USER: pastefy
      DATABASE_PASSWORD: $DB_PASSWORD__SECRET
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      SERVER_NAME: $SERVER
      AUTH_PROVIDER: NONE
      PASTEFY_LOGIN_REQUIRED: false
      PASTEFY_LOGIN_REQUIRED_CREATE: false
      PASTEFY_LOGIN_REQUIRED_READ: false
      PASTEFY_ENCRYPTION_DEFAULT: false
    ports:
      - 9980:80
    depends_on:
      - mariadb
    image: "interaapps/pastefy:latest"

What am I missing here?

**Comment by JulianFun123** [comment]
You need to [add an Authentication Provider](https://github.com/interaapps/pastefy/blob/master/README.md#adding-login) (OAuth2). For example [InteraApps OAuth2](https://quotysco.eu/InteraApps/host-pastefy-yourself-with-interaapps-accounts-oauth2).

**Comment by tamimology** [comment]
> You need to [add an Authentication Provider](https://github.com/interaapps/pastefy/blob/master/README.md#adding-login) (OAuth2). For example [InteraApps OAuth2](https://quotysco.eu/InteraApps/host-pastefy-yourself-with-interaapps-accounts-oauth2).

Awesome
Got it working now. Thanks

**Comment by ovizii** [comment]
Sorry to revive this old thread but this exactly my question:

If I run pastefy internally on my network, not exposed to the Internet without requiring any logins, I cannot delete any pastes?

like this:
```
       PASTEFY_LOGIN_REQUIRED: false
       PASTEFY_LOGIN_REQUIRED_CREATE: false
       PASTEFY_LOGIN_REQUIRED_READ: false
       PASTEFY_ENCRYPTION_DEFAULT: false
       PASTEFY_GRANT_ACCESS_REQUIRED: false
       PASTEFY_LIST_PASTES: true
       PASTEFY_PUBLIC_STATS: true
       PASTEFY_PUBLIC_PASTES: true
```
