### ISSUE TITLE
[Feature Request] Disable Signups & Password Protection

### ISSUE THREAD

**Issue by AzamServer** [interaapps/pastefy#31]
Hi.
I do not want random people creating pastes on my server and was wondering if you could make a way so that I can disable new registrations after I register myself. However, I do want a way for people without an account to read my pastes. Lastly, if you could make a way so that I could password protect some of my pastes, like Privatebin does, that would be great! Thanks!

**Comment by Tuncay-Ayhan** [comment]
> Hi. I do not want random people creating pastes on my server and was wondering if you could make a way so that I can disable new registrations after I register myself. However, I do want a way for people without an account to read my pastes. Lastly, if you could make a way so that I could password protect some of my pastes, like Privatebin does, that would be great! Thanks!

That feature is already part of Pastefy. Check out this section https://github.com/interaapps/pastefy#basic-stuff

**Comment by JulianFun123** [comment]
Hey,
there is a way to password protect your pastes:
![image](https://user-images.githubusercontent.com/42511596/175020559-0f653ecb-1b27-45aa-aa41-1ac3865534a5.png)
and there is currently no way to enable the login just for some users. 
If you want to disable the creation of pastes without login you can set `PASTEFY_LOGIN_REQUIRED_CREATE` to true.

**Comment by JulianFun123** [comment]
A way of enabling logging just for some users has been added https://github.com/interaapps/pastefy/releases/tag/6.5.0
