### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by volga629-1** [interaapps/pastefy#33]
Hello Everyone,
I am trying run application install and build without docker and getting error from npm  that install script is missing and I don't  see nothing relevant in package.json.

**Comment by JulianFun123** [comment]
What are you trying to do? You may need to go into the frontend folder

**Comment by volga629-1** [comment]
I am following guide 

```
git clone https://github.com/interaapps/pastefy.git
cd pastefy/frontend
npm run install
npm run build
cd ../backend
mvn clean package
cd ..
cp .env.example .env
nano .env
java -jar backend/target/backend.jar
```

And getting error 

```
[root@canlweb01 frontend]# npm run install
npm ERR! Missing script: "install"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm uninstall # Remove a package
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-26T23_11_45_741Z-debug-0.log
[root@canlweb01 frontend]#
```

**Comment by JulianFun123** [comment]
Oh my mistake. It's `npm install` not `npm run install`

**Comment by volga629-1** [comment]
Thank you,
Small remark for fedora36 build require to edit 

/etc/ssl/openssl.cnf

And enable options as follow 

```
[provider_sect]
default = default_sect
legacy = legacy_sect
##
[default_sect]
activate = 1
##
[legacy_sect]
activate = 1
```

Other wise build will fail with error

```
 opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],

```

Credit to 

https://stackoverflow.com/questions/72866798/node-openssl-legacy-provider-is-not-allowed-in-node-options/73064710#73064710?newreg=500d7a0e98e04cc09390c10a965c9fca
