### ISSUE TITLE
Public pastes (Everyone see everything)

### ISSUE THREAD

**Issue by alirezaalavi87** [interaapps/pastefy#34]
Hi. 
This seems like a great app but I need to be able to just dump stuff in the pastebin, and anybody who enters the bin can just see it.

I'm setting this up in my workplace for easily sharing stuff like http responses and bits of code. but pasting it here and then sending them the link to the paste seems redundant .

I thought I could achieve this with  
```
environment:
  PASTEFY_LIST_PASTES: "true"
```
in my docker compose file, but going to bin.mydomain.lan/paste  just writes Loading... 
Can I achieve this with this system?

**Comment by JulianFun123** [comment]
Currently there is no way to see all pastes in the frontend. I will add that in the near future.

**Comment by alirezaalavi87** [comment]
Ok thank you.
What is the pastefy_list_pastes variable for then?

**Comment by JulianFun123** [comment]
It just adds an API-Endpoint callef /paste.

**Comment by alirezaalavi87** [comment]
Ok thanks

**Comment by miguel-faggioni** [comment]
posting here just in case it's useful to someone else looking for this:

I've updated `backend/src/main/java/de/interaapps/pastefy/controller/PasteController.java` to force all pastes as publics:
```
@@ -59,7 +59,7 @@ public class PasteController extends HttpController {
         paste.setEncrypted(request.encrypted);
         paste.setType(request.type);

-        paste.setVisibility(request.visibility);
+        paste.setVisibility(Paste.Visibility.PUBLIC);

         if (request.forkedFrom != null) {
             Paste forkedFrom = Repo.get(Paste.class).where("key", request.forkedFrom).first();
```

then rebuilt the docker image with `docker build -t custom-pastefy/all-public .`, and updated the `docker-compose.yml` to use the new image:
```
@@ -15,7 +15,8 @@ services:
    pastefy:
      depends_on:
        - db
-     image: interaapps/pastefy:latest
+     image: custom-pastefy/all-public:latest
      ports:
        - "9999:80"
```
