### ISSUE TITLE
When registering on pastefy.ga I get a error after I try to sign in.

### ISSUE THREAD

**Issue by operationairstrike** [interaapps/pastefy#43]
Image below, looks like it tries to access a API but fails to further process the login.

![Screenshot_2023-03-15-21-05-55-953_org.mozilla.fennec_fdroid.jpg](https://user-images.githubusercontent.com/127621147/225430162-eb218c27-eee6-41c7-876f-7db10fa64ee7.jpg)

**Comment by JulianFun123** [comment]
When does this happen and when does it reoccure? I tried it with both my normal account and a completly new one and it worked for me.

**Comment by operationairstrike** [comment]
Everytime I try to log in or register.

**Comment by operationairstrike** [comment]
I'm on Fennec F Droid on Mobile

**Comment by operationairstrike** [comment]
My fault, I think my browser or ad blocker is blocking something.
