### ISSUE TITLE
Github OAuth2 not working

### ISSUE THREAD

**Issue by superhize** [interaapps/pastefy#46]
Hello,

I just finished setting up Pastefy, but for some reason, the github oauth2 do not work.

I've set the Callback URL to "http://server/api/v2/auth/oauth2/github/callback" and got this:
```json
{
  "success": false,
  "exception": "NullPointerException",
  "error": true,
  "exists": false
}
````

OAUTH2_GITHUB_CLIENT_ID and OAUTH2_GITHUB_CLIENT_SECRET are both set in docker-compose.yml

and also got the follow error in docker logs: https://pastebin.com/hq0LLzWs

**Comment by JulianFun123** [comment]
Did you set the `SERVER_NAME` environment variable as well?

**Comment by superhize** [comment]
SERVER_NAME is set to "http://localhost:9999", should i change that ? I'm using a nginx proxy.

**Comment by JulianFun123** [comment]
Hey I have tried your Website in your Github description and added the paste. prefix. When I try to log in, I get the error you sent. In the redirection URL the error is given `https://paste.hize.be/api/v2/auth/oauth2/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch`. 

`error=redirect_uri_mismatch`. You may have not set the SERVER_NAME correctly or didn't set it up correctly in your GitHub App settings

**Comment by superhize** [comment]
Homepage url is set to https://paste.hize.be/
callback url is set tp https://paste.hize.be/api/v2/auth/oauth2/github/callback
SERVER_NAME is set to https://paste.hize.be/, even tried with localhost:9999, http://localhost:9999, but nothing work

**Comment by JulianFun123** [comment]
You may want to remove the slash in the end of https://paste.hize.be. It seems to be not a problem with Pastefy itself.

**Comment by superhize** [comment]
Indeed, removing the slash in the end fixed it, thanks!
