### ISSUE TITLE
How to change Title on browser tab?

### ISSUE THREAD

**Issue by NanoG6** [interaapps/pastefy#47]
Not an issue, but how do I change that? 

<img width="236" alt="Screenshot 2023-04-30 at 09 25 16" src="https://user-images.githubusercontent.com/64691097/235332660-3c18b373-bdbe-4ae7-82bc-245779c9e866.png">

**Comment by superhize** [comment]
https://github.com/interaapps/pastefy#basic-stuff

environment:
       PASTEFY_INFO_CUSTOM_NAME: custom name

in your docker compose file, but that does not seem to work for me.

**Comment by JulianFun123** [comment]
Going to add that in the future

**Comment by JulianFun123** [comment]
Fixed in https://github.com/interaapps/pastefy/releases/tag/6.6.3

**Comment by NanoG6** [comment]
Can confirm it works now, many thanks @JulianFun123 !
