### ISSUE TITLE
Admin: Admin(s) cannot delete encrypted paste

### ISSUE THREAD

**Issue by evanferrao** [interaapps/pastefy#49]
Summary: If a paste is encrypted, then even the admin cannot delete it without a password.

Steps-to-reproduce:
(1) Make an encrypted paste as a user account
(2) Log in to admin account
(3) Try to delete the newly created paste. It prompts for a password.

Demonstration video below

[Screencast from 07-05-23 04:06:43 AM IST.webm](https://user-images.githubusercontent.com/130160624/236649089-742489f2-7296-4182-8ec0-80e370d888ce.webm)

**Comment by JulianFun123** [comment]
Fixed here https://github.com/interaapps/pastefy/releases/tag/6.6.5. (May take 20 Minutes until the image is pushed to Dockerhub)

**Comment by JulianFun123** [comment]
Btw: pastefy has an own darkmode and if you want pastefy to render the markdown file, you can just add the file extension .md to the title.

**Comment by evanferrao** [comment]
> Btw: pastefy has an own darkmode and if you want pastefy to render the markdown file, you can just add the file extension .md to the title.

Thanks, didn't know there was support for different file extensions :)
