### ISSUE TITLE
[Bug] Pastefy not working on Safari/Chrome

### ISSUE THREAD

**Issue by aazam476** [interaapps/pastefy#50]
Whenever I try to access to access my Pastefy instance using Safari/Chrome, Pastefy just downloads a file to my computer containing the following text:
```html
<strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>

```
<br>
I do have JS enabled on both browsers. When I tried using Firefox to access my Pastefy instance, it does work.

**Comment by JulianFun123** [comment]
Can you please look into your developer console and give me more detail?
