### ISSUE TITLE
docker-compose file not working

### ISSUE THREAD

**Issue by mantramantra12** [interaapps/pastefy#52]
# Problem
The `docker-compose.yaml` file seems to be outdated. I followed the steps to deploy and was given this error: 
```
pastefy-pastefy-1  | Error: at getConnection()[MySQL.java]  SQLException   Could not create connection to database server. Attempted reconnect 5 times. Giving up.
```

# Steps to reproduce
```
git clone https://github.com/interaapps/pastefy.git
cd pastefy
docker compose up
```

I noticed that the mariadb documentation (https://github.com/docker-library/docs/blob/master/mariadb/README.md) has environment variables named slightly differently to the pastefy `docker-compose.yaml`; I tried updating them to match (`MARIADB_*` instead of `MYSQL_*`) but I still got the same error.

**Comment by fame-odoo** [comment]
same here, got this issue in 6.6.6

**Comment by JulianFun123** [comment]
I'll try to look after it today

**Comment by herbst2016** [comment]
MariaDB 11+ doesn’t work.
10.11 works just fine, support until 2028, should be enough for now.

**Comment by RaneyDazed** [comment]
it works with this image just fine: `lscr.io/linuxserver/mariadb:10.6.13`. You may not necessarily want to use that image but just thought I'd mention that it works. :p

**Comment by JulianFun123** [comment]
https://github.com/interaapps/pastefy/releases/tag/6.6.7

**Comment by ovizii** [comment]
> https://github.com/interaapps/pastefy/releases/tag/6.6.7

Sorry to ask in this old thread, but what does the link to tag 6.6.7 mean? I didn't see anything MariaDB related in the changelogs. Would you mind elaborating for a second?
