### ISSUE TITLE
The base link on your API docs seems to be malicious

### ISSUE THREAD

**Issue by J0J0HA** [interaapps/pastefy#55]
I am sure this is not on intent, but the base URL (https://pastefy.ga/) on your API docs leads to a website claiming to be an antivirus scan or showing other questionable content.

Here are Screenshots of my visit (german)

![grafik](https://github.com/interaapps/pastefy/assets/80523427/07758fb3-6497-46e6-9aac-cedc5698ce71)

![grafik](https://github.com/interaapps/pastefy/assets/80523427/0fefe9b9-6ffa-44e9-add0-40ad114e08a7)

Thank you :)

**Comment by JulianFun123** [comment]
It is outdated. pastefy.app is the new Base URL. I'll take a look into it

**Comment by JulianFun123** [comment]
Fixed. Thank you. 
<img width="915" alt="Bildschirmfoto 2023-09-24 um 21 37 15" src="https://github.com/interaapps/pastefy/assets/42511596/8ce16468-cf7c-4552-a815-cd4a96ee7e7b">

**Comment by J0J0HA** [comment]
Ok, thank you :)
