### ISSUE TITLE
Run npm lint and build commands on CI

### ISSUE THREAD

**Issue by eddiejaoude** [interaapps/pastefy#6]
This will check the project is listed and builds correctly in a PR before reviewing and merging

```json
"scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
```

https://github.com/interaapps/pastefy/blob/master/frontend/package.json#L7-L8

**Comment by JulianFun123** [comment]
It is not going to pass the Gitlab-CI if the lint fails or something is broken. Vue is also going to auto-lint while developing in `npm run serve`
