### ISSUE TITLE
[Feature] Add option for disabling new user registration

### ISSUE THREAD

**Issue by arpanghosh8453** [interaapps/pastefy#62]
Basically, the title. Right now, the best you can do is require approval; why not add a simple option to disable it if someone needs that? I

I don't know how difficult that will be to implement, but It's a useful feature.

**Comment by JulianFun123** [comment]
There is the 'PASTEFY_GRANT_ACCESS_REQUIRED' environment variable with which you can enable that everyone who's registering needs your approval first. That one may help

**Comment by arpanghosh8453** [comment]
Thank you for the prompt reply! Really appreciate it. 

Like I said above, I am aware of that option and already implemented it ( working fine ). But if I decide not to have any user requesting registration? A complete disable option may be useful. 

I really like the design and features. Great job dev team :)

**Comment by JulianFun123** [comment]
Thank you very much. I will look in the future when I will implement other features. Thank you for the request.
