### ISSUE TITLE
[Bug] Users list does not show on admin page (403)

### ISSUE THREAD

**Issue by joser93** [interaapps/pastefy#73]
Greetings, I am testing pastefy admin controls but for some reason, the users api throws an 403 error, here's some details to take in consideration.

Current setup:
- Google Oauth
- Login required for create only
- Grant access required
- Changed the server name with the domain assigned with a Nginx proxy.

Simplified Steps to reproduce:
1. Setup the oauth and login for the first time
2. Go to `/admin`
3. Click on users

Extended steps:
1. Deploy instance with docker-compose
2. Setup the nginx proxy using nginx proxy manager
3. Modifiy the docker compose file and allow Google oauth and following the redirect from other issue, then deploy the server again
4. Login with my Google accounf for the first time, so I can have admin privileges. (Login works)
5. Allow grant access and login required for create only flags, then redeploy
6. Login with other Google account and wait to admin permission
7. Use my account to allow the other user, access to `/admin`
8. Click on users

Expected behavior:
List of users in the server and manage the users. 

Current behavior:
The list does not load due an 403 request at /api/v2/admin/users?page=1 with the following result:

```json
{
    "success": false,
    "exception": "PermissionsDeniedException",
    "error": true,
    "exists": false
}
```

![image](https://github.com/user-attachments/assets/60366b8b-333d-41f2-b8e5-1ec49eb9aea2)

Any hint for this?
Thanks

**Comment by JulianFun123** [comment]
Can you look into the web-servers container logs and share them? And did you set your type as ADMIN in the database for your user?

**Comment by joser93** [comment]
@JulianFun123 Thanks for your reply. Actually, yes, my user had assigned a type USER in the DB, so, to fix it did it with a db update 

```sql
UPDATE pastefy_users SET type=ADMIN WHERE id='<my_user_id>';
```

But, is this expected to happen? is  there a setup process to assign the first user as admin or did I missed something?

For the issue track, I'll close it as solved and not to mix the conversation if needed another issue to talk  about handlng admin privileges for the first user.

Thanks.
